-- Seed data for Relationship CRM
--
-- The seed_data(p_user_id uuid) function lives in
-- supabase/migrations/20260430999700_slice7a5_full_prod_mirror.sql (Slice 7A.5)
-- as part of versioned schema history. It is no longer (re)defined here.
--
-- After signing up, run:  select seed_data('your-user-id-here');
