import { execSync } from "node:child_process";
import { FailureCard } from "./parse-reds";
import { Worktree } from "./worktree";
import { CheckRecord } from "../../lib/invariants";

export type PrResult = { url: string; number: number };

function buildBody(opts: {
  card: FailureCard;
  before: { severity: string; smell: string };
  after: CheckRecord;
  filesChanged: number;
  reportDate: string;
}): string {
  const { card, before, after, filesChanged, reportDate } = opts;
  return [
    `Auto-triage fix: \`${card.check_id}\``,
    "",
    `Triggered by \`audits/reports/audit-${reportDate}.json\`. Orchestrator: \`audits/triage/run-triage.ts\`.`,
    "",
    "## Before",
    "",
    `- severity: **${before.severity}**`,
    `- smell: ${before.smell}`,
    "",
    "## After",
    "",
    `- severity: **${after.result.severity}**`,
    `- pass: ${after.result.pass}`,
    `- smell: ${after.result.smell ?? "(none)"}`,
    `- duration: ${after.durationMs}ms`,
    "",
    "## Scope",
    "",
    `- files modified: ${filesChanged}`,
    `- layer: ${card.layer}`,
    `- runner: \`${card.runner_source}\``,
    "",
    "## Verification",
    "",
    "```bash",
    card.rerun_command,
    "```",
    "",
    "Re-run by the orchestrator immediately after the sub-agent finished. Output captured above.",
  ].join("\n");
}

export function openPr(opts: {
  worktree: Worktree;
  card: FailureCard;
  before: { severity: string; smell: string };
  after: CheckRecord;
  filesChanged: number;
  reportDate: string;
  draft: boolean;
}): PrResult {
  const body = buildBody(opts);
  const draftFlag = opts.draft ? "--draft" : "";
  const out = execSync(
    `cd "${opts.worktree.path}" && gh pr create --title "auto-triage: ${opts.card.check_id}" --body $'${body.replace(/'/g, "'\\''")}' ${draftFlag} --base main --head "${opts.worktree.branch}"`,
    { encoding: "utf8", shell: "/bin/bash" },
  ).trim();

  const url = out.split("\n").pop() ?? out;
  const match = url.match(/\/pull\/(\d+)/);
  return { url, number: match ? Number(match[1]) : 0 };
}

export function commitChanges(worktree: Worktree, checkId: string): number {
  const status = execSync(`git -C "${worktree.path}" status --porcelain`, { encoding: "utf8" });
  const filesChanged = status.split("\n").filter((l) => l.trim()).length;
  if (filesChanged === 0) return 0;
  execSync(`git -C "${worktree.path}" add -A`, { encoding: "utf8" });
  execSync(
    `git -C "${worktree.path}" commit -m "auto-triage: ${checkId}" -m "Generated by audits/triage/run-triage.ts"`,
    { encoding: "utf8" },
  );
  return filesChanged;
}
