-- Berneil broker-open luxury list import (208 NEW contacts)
-- Source: ~/Downloads/listing_member_contacts.csv (443 rows deduped). MLS office codes stripped.
-- Name fixes: dropped 1 corrupted row; "R M Joe"->Joe Bushong; "Maximilian Schopen"/"De Melo"->Maximilian/"Schopen De Melo".
-- account_id + user_id sourced from existing contacts (prod OWNER_USER_ID env blank).
-- Dedup: email canonical; no-email twins dropped; EXISTING excluded via NOT EXISTS. Idempotent. Tag+insert ONLY.

with incoming (first_name, last_name, email, phone, brokerage) as (
  values
  ('Libby', 'Cohen', 'libby@libbycohen.com', '602-291-1446', 'RETSY'),
  ('David', 'Elton', 'davidelton97@gmail.com', '480-226-3711', 'Arizona Best Real Estate'),
  ('Karen', 'Ganz', NULL, NULL, 'Local Luxury Christie''s International Real Estate'),
  ('Fred', 'Dougherty', 'fred.dougherty@gmail.com', '602-526-0424', 'HomeSmart'),
  ('Leif', 'Swanson', 'LeifSwanson@hotmail.com', '602-686-3852', 'Realty ONE Group'),
  ('Katrina', 'Barrett', 'katrina@localluxuryre.com', '520-403-5270', 'Local Luxury Christie''s International Real Estate'),
  ('Jo Ann', 'Bauer', NULL, NULL, 'Coldwell Banker Realty'),
  ('Jodi', 'Geiger', 'jgeiger@hsmove.com', '602-321-4149', 'HomeSmart'),
  ('Deborah', 'Frazelle', 'debbie@debbiefrazelle.com', '602-399-8540', 'Coldwell Banker Realty'),
  ('Julie', 'Rohr', 'julierohr@gmail.com', '602-317-5667', 'RETSY'),
  ('Joe', 'Bushong', 'joe.bushong@russlyon.com', '602-770-6733', 'Russ Lyon Sotheby''s International Realty'),
  ('Erin', 'Denk', 'ErinDenk@RETSY.com', '602-525-7717', 'RETSY'),
  ('Kristina', 'Spellman', 'Kristina@localluxuryre.com', '602-717-5582', 'Local Luxury Christie''s International Real Estate'),
  ('Laura', 'Jorden', 'laura@laurajorden.com', '480-734-0870', 'Compass'),
  ('George', 'Wanner', 'geozona@aol.com', '480-203-1506', 'Keller Williams Realty Sonoran Living'),
  ('Chris', 'Morrison', 'chris@retsy.com', '602-456-0065', 'RETSY'),
  ('Heather', 'Wilson', 'heatherwilson@retsy.com', '602-206-1814', 'RETSY'),
  ('Kelly', 'Cook', 'clientcare@cookandassociatesaz.com', '480-442-9868', 'Real Broker'),
  ('Grant', 'Almquist', 'grant.almquist@russlyon.com', '602-615-2799', 'Russ Lyon Sotheby''s International Realty'),
  ('Kristopher', 'Sollenberger', 'kris.sollenberger@russlyon.com', '310-365-0368', 'Russ Lyon Sotheby''s International Realty'),
  ('Yevgeniy', 'Patent', 'gene@clutchaz.com', '480-371-0888', 'Compass'),
  ('Mark', 'Vanderlinde', 'markvrealestategroup@gmail.com', NULL, 'RE/MAX Fine Properties'),
  ('Frank', 'Aazami', 'frank@pcgagents.com', '480-266-0240', 'Compass'),
  ('Christopher', 'Karas', 'chris@thekarasgroup.com', '602-919-6511', 'Compass'),
  ('Scott', 'Grigg', 'Scott@thealtmanbrothersgriggsaz.com', '480-540-5479', 'Grigg''s Group Powered by The Altman Brothers'),
  ('Lauren', 'Ellington', 'laurenellingtonaz@gmail.com', '602-326-9586', 'Fathom Realty Elite'),
  ('Julie', 'Pelle', 'jpelle@juliepelle.com', '480-323-6763', 'Compass'),
  ('Garrick', 'O''Connell', 'garrick.oconnell@gmail.com', '760-505-2520', 'Venture REI, LLC'),
  ('Alex', 'Goldstein', 'alex@luxeaz.com', '480-442-7325', 'Realty ONE Group'),
  ('Eric', 'Nyquist', 'eric.nyquist@gmail.com', '480-580-5044', 'My Home Group Real Estate'),
  ('Barry', 'Van Patten II', 'barry.vanpatten2@russlyon.com', '602-576-2019', 'Russ Lyon Sotheby''s International Realty'),
  ('Babbi', 'Gabel', 'babbi.gabel@gmail.com', '602-741-7750', 'RETSY'),
  ('Robert', 'Joffe', 'robert@thejoffegroup.com', '602-989-8300', 'Compass'),
  ('Christina', 'Hizme', 'krista@retsy.com', '602-740-6354', 'RETSY'),
  ('Renu', 'Bhargava', 'renusellsarizona@gmail.com', '480-980-1139', 'Berkshire Hathaway HomeServices Arizona Properties'),
  ('Kory', 'Gilliland', 'Kory.Gilliland1@gmail.com', '602-791-2151', 'Ironwood Fine Properties'),
  ('Carol', 'Adams', 'caroladams5828@gmail.com', '480-329-4682', 'Compass'),
  ('Michelle', 'Kort', 'michelle@michellekort.com', '602-750-2520', 'Compass'),
  ('Joan', 'Levinson', 'joan@joanlevinson.com', '480-543-0006', 'Realty ONE Group'),
  ('Danielle', 'Walls', 'danielle@amazingstaging.email', '480-636-0155', 'Compass'),
  ('Jim', 'Steimer', NULL, NULL, 'AZ Brokerage Holdings, LLC'),
  ('Lee', 'Courtney', 'lee@leecourtney.com', '480-296-5922', 'West USA Realty'),
  ('Rosie', 'Derryberry', 'rosiederryberry@gmail.com', '480-703-7673', 'Real Broker'),
  ('Joshua', 'Peters', 'josh@statelyliving.com', '480-788-7556', 'Realty ONE Group'),
  ('Jerome', 'Drake', NULL, NULL, 'Arizona Sunset Realty'),
  ('Vincent', 'Clark', 'vc@vincentclarkRE.com', '602-684-9355', 'VCRE'),
  ('Christopher', 'Doyle', 'Chrisdoylerealty@outlook.com', '602-527-8841', 'Realty ONE Group'),
  ('Catherine', 'Jacobson', 'Catherine@catherinejacobson.com', '602-790-1992', 'Local Luxury Christie''s International Real Estate'),
  ('Samuel', 'Jandel', 'sam.jandel@gmail.com', '937-418-4595', 'Compass'),
  ('Karen', 'DeGeorge', 'sold@degeorgepartners.com', '480-225-3766', 'Russ Lyon Sotheby''s International Realty'),
  ('Peter', 'Zaidan', 'Homes4CarGuys@gmail.com', '610-996-7771', 'Russ Lyon Sotheby''s International Realty'),
  ('Craig', 'Young', NULL, NULL, 'REI Marketing'),
  ('Sean', 'Steimer', NULL, NULL, 'AZ Brokerage Holdings, LLC'),
  ('Beth Jo', 'Zeitzer', 'bethjozeitzer@roiproperties.com', '602-319-1326', 'R.O.I. Properties'),
  ('Christy', 'Rios', 'christyriosgroup@gmail.com', '602-565-4851', 'Keller Williams Integrity First'),
  ('Zachary', 'Cates', 'zach.cates@icloud.com', '602-369-0140', 'PROS Realty LLC'),
  ('Zachary', 'Hawker', 'mrrealtoraz@gmail.com', '480-316-2718', 'Compass'),
  ('Michael', 'Lehman', 'mlehman@silverleaf.com', '480-734-7271', 'Silverleaf Realty'),
  ('Martha', 'Andrews', 'martha@xsellaz.com', '480-577-7311', 'Keller Williams Arizona Realty'),
  ('Mikhail', 'Quijada', NULL, NULL, 'The Brokery'),
  ('Laura Lee', 'Cahal', 'llcahal@gmail.com', '602-770-6576', 'Compass'),
  ('Ephrem', 'Jando', 'ej@ephremjando.com', '480-206-3631', 'Real Broker'),
  ('Thomas', 'Scott', 'thomas@elevationgroupaz.com', '480-482-9260', 'Grigg''s Group Powered by The Altman Brothers'),
  ('Heather', 'Flom', 'hflom@tjh.com', '623-225-6936', 'Thomas James Homes'),
  ('Heather', 'Novak', 'Heather@localluxuryre.com', '480-603-5900', 'Local Luxury Christie''s International Real Estate'),
  ('Mike', 'Domer', 'mike@mikedomer.com', '480-861-8883', 'Compass'),
  ('Deborah', 'Beede', 'debbie.beede@russlyon.com', '602-373-6353', 'Russ Lyon Sotheby''s International Realty'),
  ('Thomas', 'Osterman', NULL, NULL, 'AZ Brokerage Holdings, LLC'),
  ('Michael', 'Bergs', 'mikey.allredteam@gmail.com', '602-377-7620', 'DRB Homes'),
  ('Heather', 'MacLean', 'areasuccess@gmail.com', '602-214-5169', 'Compass'),
  ('Cionne', 'McCarthy', 'Cionne.McCarthy@russlyon.com', '602-619-4550', 'Russ Lyon Sotheby''s International Realty'),
  ('Amar', 'Kohli', 'kohli.amar@gmail.com', '480-330-2927', 'HomeSmart'),
  ('Joyce', 'Lynch', 'joycelynchrealestate@gmail.com', '602-722-1668', 'Russ Lyon Sotheby''s International Realty'),
  ('Jennifer', 'Felker', 'felkeraz@yahoo.com', '602-881-8088', 'Compass'),
  ('Eilise', 'Sala', NULL, NULL, 'Berkshire Hathaway HomeServices Arizona Properties'),
  ('Nicholas', 'Toon', 'Nick@ToonCoRealEstate.com', '480-602-3888', 'RETSY'),
  ('Brad', 'Goddes', 'brad@goddeshomes.com', '602-903-7209', 'Goddes Homes'),
  ('Mary', 'Grassl', 'mary@retsy.com', '602-330-6353', 'RETSY'),
  ('Lisa Marvel', 'Tull', 'lmarveltull@gmail.com', '480-318-1618', 'The Agency'),
  ('David', 'Segal', 'David@BuyFixSellSig.com', '602-740-0669', 'Realty USA Southwest'),
  ('Bobby', 'Lieb', 'boblieb@aol.com', '602-376-1341', 'Compass'),
  ('Jonnea', 'Bennett', 'jonneab@camelothomes.com', '602-818-3725', 'Camelot Homes, Inc.'),
  ('Yvonne', 'Cahill', 'sales@thebestazagent.com', '602-684-3290', 'HomeSmart'),
  ('Cory', 'Mishkin', 'cory@cambridgeproperties.com', '602-820-9000', 'Cambridge Properties'),
  ('Karen', 'Armstrong', 'karen@investAZre.com', '602-369-0767', 'Armstrong Properties'),
  ('Wendy', 'Herst', 'wendy@wendyherst.com', '480-788-9404', 'DeLex Realty'),
  ('Delaney', 'Rotta', 'delaney@delaneyrotta.com', '825-935-2112', 'Compass'),
  ('Hans', 'Horchler', 'Hans.Horchler@RussLyon.com', '602-619-1267', 'Russ Lyon Sotheby''s International Realty'),
  ('Alex', 'Smith', 'alex@smithphx.com', '480-459-7111', 'RETSY'),
  ('Lisa', 'Westcott', 'Lisa@thewgroupaz.com', '480-229-3455', 'RETSY'),
  ('Lisa', 'Roberts', 'lisa@lisaroberts.com', '480-232-3291', 'Russ Lyon Sotheby''s International Realty'),
  ('Jennifer', 'Burgess', 'jennifer@retsy.com', '602-999-5988', 'RETSY'),
  ('Beth', 'Thompson', 'bthompsonre@gmail.com', '602-740-3161', 'Compass'),
  ('David', 'Roth', 'davidrothaz@gmail.com', '602-556-0048', 'The Fenix Realms'),
  ('George', 'Laughton', 'info@laughtonteam.com', '623-256-6510', 'My Home Group Real Estate'),
  ('Zhobin', 'Jawanmardi', 'zhobin.jawanmardi@gmail.com', '602-828-4995', 'Compass'),
  ('Eve', 'Treger', 'eve@vicsdale.com', '602-697-7663', 'Vicsdale'),
  ('Matthew', 'Altman', 'staff@thealtmanbrothers.com', '323-791-9398', 'Grigg''s Group Powered by The Altman Brothers'),
  ('Nicholas', 'Carlson', 'Nick@CarlsonCollectiveAz.com', '480-200-9471', 'Compass'),
  ('Jennifer', 'Stone', 'jstone.azgroup@gmail.com', '480-529-4399', 'RETSY'),
  ('Michael', 'Syltebo', 'michael@phxhistoric.com', '425-652-6573', 'Bushnell Real Estate Solutions'),
  ('Beverly', 'Young', 'bevyoungre@gmail.com', '208-870-9966', 'Compass'),
  ('Anita', 'Best', NULL, NULL, 'The Agency'),
  ('Angel', 'Ureta', 'angel.ureta@compass.com', '520-351-2457', 'Compass'),
  ('Jennifer', 'Bolen', NULL, NULL, 'Russ Lyon Sotheby''s International Realty'),
  ('Brian', 'North', 'brian@abresi.com', '480-250-6687', 'Compass'),
  ('Whitney', 'St. Clair', 'whitneyestclair@gmail.com', '949-397-7070', 'Compass'),
  ('William', 'Bourgeois', 'billy@hautproperties.com', '480-463-4746', 'HomeSmart'),
  ('Patrice', 'Pimentel', 'patrice4homes@gmail.com', '425-214-6201', 'Realty ONE Group'),
  ('Peyton', 'September', 'homes@peytonseptember.com', '480-459-8168', 'Compass'),
  ('Michel', 'Edery', 'jm@luxuryliving.ai', '480-747-4795', 'Russ Lyon Sotheby''s International Realty'),
  ('Matthew', 'Smithlin', 'msmithlin@hsmove.com', '602-327-5844', 'HomeSmart'),
  ('Tillie', 'Jenkins', 'tillie.jenkins@russlyon.com', '602-882-3301', 'Russ Lyon Sotheby''s International Realty'),
  ('Jeremy', 'Brown', 'jeremybrown.re@gmail.com', '480-251-4321', 'My Home Group Real Estate'),
  ('Andrew', 'Beardsley', 'abeardsley@silverleaf.com', '602-399-3507', 'Silverleaf Realty'),
  ('Anne', 'Lanker', 'anne@anneshomes.com', '602-803-1866', 'RETSY'),
  ('Heather', 'Gagne', 'heathergagne7@gmail.com', '480-302-0633', 'Compass'),
  ('Jason', 'Glimcher', 'Jason@TheGlimcherTeam.com', '480-695-8196', 'Compass'),
  ('Maximilian', 'Schopen De Melo', 'max@mp-realestate.com', '480-907-9660', 'Local Luxury Christie''s International Real Estate'),
  ('Thuy', 'Pham', 'thuy@thewilliamsre.com', '602-999-9469', 'HomeSmart'),
  ('Robert', 'Mann', 'brendan@tsgluxury.com', '602-313-8688', 'The Solvere Group, LLC'),
  ('Deborah', 'Sinani', NULL, NULL, 'The Agency'),
  ('Kristen', 'Youn', 'kristen@revanarealty.com', '480-747-0066', 'Revana Realty'),
  ('Allan', 'Macdonald', 'allan@foreazhomes.com', '480-220-9724', 'Russ Lyon Sotheby''s International Realty'),
  ('Bill', 'Bulaga', NULL, NULL, 'Russ Lyon Sotheby''s International Realty'),
  ('Eric', 'Gedalje', 'eric@thehavasulife.com', '323-477-4631', 'eXp Realty'),
  ('Ilia', 'Qoshlli', 'eurokelas@gmail.com', '602-402-5013', 'DeLex Realty'),
  ('JW', 'Richie', 'jw@camelbackluxuryliving.com', '480-843-5101', 'Compass'),
  ('Sean', 'Elton', 'seanelton@gmail.com', '602-451-1625', 'HomeSmart'),
  ('Rick', 'Metcalfe', 'offers@canamrealty.com', '480-759-2242', 'Canam Realty Group'),
  ('Bryan', 'OConor', 'bryan@arcadiafortress.com', '480-275-0812', 'Compass'),
  ('Jonathan Michael', 'Leaman', NULL, NULL, 'America One Luxury Real Estate'),
  ('Mike', 'Mendoza', 'mike@mendozateam.com', '602-430-3917', 'Keller Williams Realty Sonoran Living'),
  ('Farrah Dee', 'Greeson', 'farrahgreeson@gmail.com', '225-721-3018', 'Compass'),
  ('Don', 'Matheson', 'don@scottsdalerealestate.com', '602-694-3200', 'RE/MAX Fine Properties'),
  ('Samantha Riley', 'Kates', 'samanthakatesre@gmail.com', '602-384-4660', 'Compass'),
  ('Carol', 'Noto', 'cnsells4u@gmail.com', '480-734-8222', 'HomeSmart'),
  ('Frank', 'Dimaggio', 'frank@theagencyfrank.com', '602-469-2554', 'The Agency'),
  ('Michelle Meglio', 'Macklin', NULL, NULL, 'Platinum Living Realty'),
  ('Patrick', 'Keon', 'pkeon@me.com', '480-686-4663', 'DeLex Realty'),
  ('Josh', 'Hintzen', 'Josh@MoJoScottsdale.com', '480-659-6569', 'Real Broker'),
  ('Greg', 'Markov', 'greg@phoenixheritage.com', '602-451-5826', 'HomeSmart'),
  ('Megan', 'Smith', 'megan@thebrokery.com', '661-644-9287', 'The Brokery'),
  ('Pushpit', 'Tandon', 'push@aznewman.com', '623-385-9451', 'Real Broker'),
  ('Patricia Anne', 'Gore', 'trish@trishgore.com', '480-295-6062', 'Coldwell Banker Realty'),
  ('Philip', 'Chadwick', 'phil@philchadwick.com', '602-738-6971', 'Coldwell Banker Realty'),
  ('Kristen', 'Ryan', 'kristyryan@remax.net', '480-688-2429', 'RE/MAX Fine Properties'),
  ('Suzanne', 'Miller', 'suzimilleraz@gmail.com', '480-695-3003', 'Russ Lyon Sotheby''s International Realty'),
  ('Christopher', 'Meyer', 'Chris@MrRealEstateAZ.com', '602-885-4663', 'Compass'),
  ('Lauren', 'Wendt', 'lauren@wandpartners.co', '602-828-5767', 'W and Partners, LLC'),
  ('Efmorfia', 'Apostolis', 'morfiaazagent@gmail.com', '480-322-6404', 'eXp Realty'),
  ('Gavriel', 'Yagudayev', 'gary@levyresales.com', '623-418-8302', 'eXp Realty'),
  ('Cheryl', 'D''Anna', 'cheryl.danna@russlyon.com', '480-319-3800', 'Russ Lyon Sotheby''s International Realty'),
  ('Peter', 'Burch', 'phxburch@gmail.com', '602-614-5574', 'ML CO Realty'),
  ('Robin', 'Orscheln', 'robin@roluxurygroup.com', '602-380-8735', 'Compass'),
  ('James', 'Wexler', 'James@JamesWexler.com', '480-221-8080', 'Jason Mitchell Real Estate'),
  ('Larissa', 'Hoss', 'larissa@lhrealtor.com', '480-212-2267', 'Compass'),
  ('Jim', 'Bruske', NULL, NULL, 'Engel & Voelkers Scottsdale'),
  ('Artie', 'Baxter', 'artiebaxter@localluxuryre.com', '310-428-0225', 'Local Luxury Christie''s International Real Estate'),
  ('Susan', 'Polacek', 'susanpazhomes@yahoo.com', '480-267-8825', 'HomeSmart'),
  ('Greg', 'Hidder', 'greg@greghidder.com', '602-980-7199', 'Compass'),
  ('Jon', 'Condo', 'jon@joncondo.com', '925-785-3001', 'Compass'),
  ('Laura', 'Briggs', 'laura@scottsdalelux.com', '480-550-1208', 'Russ Lyon Sotheby''s International Realty'),
  ('Adam', 'Hizme', 'adam@retsy.com', '480-203-3423', 'hizme RETSY'),
  ('Virginia', 'Gee', 'virginia.gee@russlyon.com', '602-526-2672', 'Russ Lyon Sotheby''s International Realty'),
  ('Dave', 'Westbrook', NULL, NULL, 'Urban Luxe Real Estate'),
  ('David', 'Larchez', 'DavidLarchez@gmail.com', '480-822-8898', 'larchez/ Compass'),
  ('Jesse', 'Kibler', 'jkibler21@gmail.com', '480-999-4064', 'HomeSmart'),
  ('Veronica', 'Estrada', NULL, NULL, 'RETSY'),
  ('Joseph', 'Reifman', 'joe.reifman@gmail.com', '602-349-0157', 'HomeSmart'),
  ('Katie', 'Baccus', 'katie@baccusrealtygroup.com', '480-206-4336', 'Compass'),
  ('Erik', 'Gocken', 'erikgocken@gmail.com', '602-451-1605', 'Global Real Estate Investments'),
  ('Michael', 'Garren', 'mike@garrengroupaz.com', '480-284-3069', 'Crossroads Brokerage'),
  ('Richard', 'Boys', 'kipboys@gmail.com', '602-619-7831', 'HomeSmart'),
  ('Neil', 'Lende', 'ScottsdaleRealtor@yahoo.com', '602-791-4319', 'Fathom Realty Elite'),
  ('Daniel', 'Yonker', 'dan@yonkergroup.com', '206-327-4821', 'Grigg''s Group Powered by The Altman Brothers'),
  ('Gretchen', 'Baumgardner', NULL, NULL, 'Engel & Voelkers Scottsdale'),
  ('Michelle', 'Anderson', 'michelleandersonaz@gmail.com', '480-201-5577', 'HomeSmart'),
  ('Roger', 'Malcolm', 'rogmalcolm@aol.com', '602-430-0285', 'Realty Executives Arizona Territory'),
  ('Kirk', 'Linehan', NULL, NULL, 'RETSY'),
  ('Gabriel', 'Petratis', 'gpetratis@fineprop.com', '480-869-4910', 'RE/MAX Fine Properties'),
  ('Patrick', 'Niederdrenk', NULL, NULL, 'America One Luxury Real Estate'),
  ('Joelle', 'Addante', 'joelle@phoenixliving.com', '602-790-6484', 'Compass'),
  ('Brian', 'Frey', 'brian@retsy.com', '602-402-3050', 'RETSY'),
  ('Jennifer', 'Kourouglos', 'jennifer@azluxuryhomegroup.com', '480-263-0992', 'Compass'),
  ('Hank', 'Gries', 'hank@veloparkpro.com', '602-451-6033', 'RETSY'),
  ('Jarrod', 'Smith', 'jsmithbroker@mac.com', '602-432-4743', 'Plush Arizona Living'),
  ('Adrian', 'Heyman', NULL, NULL, 'The Agency'),
  ('Brooke', 'Fair', 'brooke@retsy.com', '480-240-8375', 'RETSY'),
  ('Laura', 'Jewett', NULL, NULL, 'Platinum Living Realty'),
  ('Shaianne', 'Coleman', 'shaianne@emerylanehomes.com', '623-201-9261', 'RETSY'),
  ('Suzanne', 'Gammage', 'suzanne@suzannegammage.com', '480-612-2444', 'Russ Lyon Sotheby''s International Realty'),
  ('Silje', 'Garner', 'silje@bedbrock.com', '602-617-0320', 'Bedbrock Real Estate Company'),
  ('Mark', 'Thomas', 'mark.thomas@russlyon.com', '201-707-0543', 'Russ Lyon Sotheby''s International Realty'),
  ('Beau Carson', 'Browder', 'beauazrealty@gmail.com', '623-249-0697', 'Phoenix Property Group'),
  ('Shawna', 'Warner', 'shawna@retsy.com', '602-743-7006', 'RETSY'),
  ('Elizabeth', 'Corti', 'elizabeth@theavecollective.com', '480-268-6471', 'The Ave Collective'),
  ('Shelby', 'DiBiase', 'shelby@dibiaseteam.com', '602-330-1985', 'eXp Realty'),
  ('Tracy', 'Fitzgerald', 'tracy.fitzgerald@TheNobleAgency.com', '480-560-7000', 'The Noble Agency'),
  ('Jonathan', 'Wall', 'jwall32@cox.net', '602-527-0088', 'DPR Realty LLC'),
  ('David', 'Newcombe', 'david@davidnewcombe.com', '602-510-0111', 'Compass'),
  ('Sue', 'Shapiro', 'sue.shapiro@russlyon.com', '602-809-9242', 'Russ Lyon Sotheby''s International Realty'),
  ('Sandra', 'Gaare', 'sandra@retsy.com', '847-922-2620', 'RETSY'),
  ('Andrea', 'Sammons', NULL, NULL, 'Grigg''s Group Powered by The Altman Brothers'),
  ('Cheryl', 'Anderson', 'cheryl@cherylanderson.com', '602-312-6038', 'Russ Lyon Sotheby''s International Realty'),
  ('Marissa', 'Kline', 'marissa@thekarasgroup.com', '602-821-4479', 'Compass'),
  ('Sabrina', 'James', 'Sabrina@SilverSkyPV.com', '480-440-2065', 'Local Luxury Christie''s International Real Estate'),
  ('Johnathon', 'De Young', 'johnathondeyoung@me.com', '480-619-0780', 'Russ Lyon Sotheby''s International Realty')
),
to_insert as (
  select i.*
  from incoming i
  where (i.email is not null
         and not exists (select 1 from public.contacts c where lower(c.email) = lower(i.email)))
     or (i.email is null
         and not exists (select 1 from public.contacts c
                         where lower(c.full_name) = lower(i.first_name || ' ' || i.last_name)))
)
insert into public.contacts
  (first_name, last_name, email, phone, type, brokerage, tags, source, user_id, account_id)
select
  first_name, last_name, email, phone,
  'realtor',
  brokerage,
  array['luxury-5mil-plus','BerneilBlast']::text[],
  'berneil-broker-open-2026-05-29-import',
  'b735d691-4d86-4e31-9fd3-c2257822dca3'::uuid,
  'd2c8793f-f0b8-4b24-a47d-7b2387f8e7f0'::uuid
from to_insert;
