-- ============================================================
-- MORNING RELATIONSHIP BRIEF (Phase 1)
-- Table:  morning_briefs
-- RLS:    alex-only, keyed on auth.jwt() ->> 'email'
-- ============================================================
-- Plan:   ~/.claude/plans/curried-tinkering-finch.md (Step 1)
-- Generated: 2026-04-24
--
-- How to run:
--   Open Supabase SQL Editor. Paste this file. Run. Expect "COMMIT".
--
-- Idempotent: DROP TABLE IF EXISTS CASCADE before CREATE.
--   Re-running this file rebuilds the morning_briefs schema only.
--   morning_briefs is new in this slice; no data loss on first run.
--   On re-run, all morning_briefs rows are wiped.
--   Do not re-run after the cron has populated rows you care about.
--
-- Versioning contract:
--   One row per brief_date (UTC date in MST tz, formatted YYYY-MM-DD).
--   Cron upserts on brief_date. generated_at bumps on each run.
--   Never DELETE; soft-delete via deleted_at if a row needs to be hidden.
--
-- Soft delete (standing rule 3):
--   morning_briefs carries deleted_at TIMESTAMPTZ NULL. No hard deletes.
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- Clean slate (idempotency)
-- ------------------------------------------------------------
DROP TABLE IF EXISTS public.morning_briefs CASCADE;

-- ------------------------------------------------------------
-- morning_briefs: nightly relationship brief output
-- ------------------------------------------------------------
CREATE TABLE public.morning_briefs (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brief_date      DATE NOT NULL,
  generated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  brief_json      JSONB NOT NULL,
  brief_text      TEXT NOT NULL,
  model           TEXT NOT NULL,
  usage           JSONB,
  contacts_scored INT NOT NULL DEFAULT 0,
  errors          JSONB,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at      TIMESTAMPTZ
);

COMMENT ON TABLE public.morning_briefs IS
  'Nightly relationship brief assembled at 12:30 UTC (5:30am MST). One row per brief_date.';
COMMENT ON COLUMN public.morning_briefs.brief_date IS
  'The day this brief is FOR (YYYY-MM-DD in MST). Unique per non-deleted row.';
COMMENT ON COLUMN public.morning_briefs.brief_json IS
  'Structured brief data: { temperature_ranking, congrats_queue, watch_list, one_thing }.';
COMMENT ON COLUMN public.morning_briefs.brief_text IS
  'Narrative markdown rendered at /morning. Generated by Claude API.';
COMMENT ON COLUMN public.morning_briefs.usage IS
  'Anthropic usage telemetry: { input_tokens, output_tokens, cache_read_tokens, cache_creation_tokens }.';
COMMENT ON COLUMN public.morning_briefs.errors IS
  'Per-contact non-fatal errors encountered during scoring. NULL on clean runs.';

-- ------------------------------------------------------------
-- Indexes
-- ------------------------------------------------------------
-- One brief per date (live rows only). Cron upserts via this index.
CREATE UNIQUE INDEX morning_briefs_brief_date_unique
  ON public.morning_briefs (brief_date)
  WHERE deleted_at IS NULL;

-- Latest-first lookup for /morning route.
CREATE INDEX morning_briefs_generated_at_idx
  ON public.morning_briefs (generated_at DESC)
  WHERE deleted_at IS NULL;

-- ------------------------------------------------------------
-- RLS: alex-only, JWT email pattern
-- ------------------------------------------------------------
ALTER TABLE public.morning_briefs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "alex_morning_briefs_all" ON public.morning_briefs;
CREATE POLICY "alex_morning_briefs_all" ON public.morning_briefs
  FOR ALL TO authenticated
  USING      (auth.jwt() ->> 'email' = 'alex@alexhollienco.com')
  WITH CHECK (auth.jwt() ->> 'email' = 'alex@alexhollienco.com');

COMMIT;

-- ============================================================
-- Verify (run after COMMIT, optional sanity check):
--
--   SELECT relname, relrowsecurity
--     FROM pg_class
--    WHERE relname = 'morning_briefs';
--   -- expect 1 row, relrowsecurity = true
--
--   SELECT indexname FROM pg_indexes
--    WHERE tablename = 'morning_briefs';
--   -- expect: morning_briefs_pkey,
--   --         morning_briefs_brief_date_unique,
--   --         morning_briefs_generated_at_idx
--
--   SELECT polname FROM pg_policy
--    WHERE polrelid = 'public.morning_briefs'::regclass;
--   -- expect: alex_morning_briefs_all
-- ============================================================
